name: Build and Export

on:
  push:
    branches: [ main ]
env:
  GODOT_VERSION: 3.4.4
  TARGET: release_win_x64
  
jobs:
  winx64:
    runs-on: ubuntu-latest
    name: Windows x64 Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Godot Templates
        run: |
            url=https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/mono/Godot_v$GODOT_VERSION-stable_mono_export_templates.tpz
            zip=~/.local/share/godot/templates/Godot_v$GODOT_VERSION-stable_mono_export_templates.tpz
            
            mkdir -p ~/.local/share/godot/templates
            wget $url -P ~/.local/share/godot/templates/
            unzip $zip -d ~/.local/share/godot/templates/
            mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/$GODOT_VERSION.stable.mono
            rm $zip
            
      - name: Download Godot Headless Engine
        run: |
            url=https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/mono/Godot_v$GODOT_VERSION-stable_mono_linux_headless_64.zip
            
            mkdir .tools
            wget $url -P .tools/
            unzip .tools/Godot_v$GODOT_VERSION-stable_mono_linux_headless_64.zip -d .tools
            rm .tools/Godot_v$GODOT_VERSION-stable_mono_linux_headless_64.zip
      - name: Export
        run: |
            mkdir -p .publish/$TARGET 
            .tools/Godot_v$GODOT_VERSION-stable_mono_linux_headless_64/Godot_v$GODOT_VERSION-stable_mono_linux_headless.64 --export $TARGET --path ./src
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: run-foxy-run-winx64
          path: .publish/${{ env.TARGET }}